name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 또는 다른 브랜치 이름

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 소스 코드
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.MAC_GITACTION }} | docker login -u havi98 --password-stdin
      env:
        DOCKER_PASSWORD: ${{ secrets.MAC_GITACTION }}

    - name: Build and Push Docker Image
      env:
        NAME: havi98
        REPO: mac_gitaction
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $NAME/$REPO:latest .
        docker push $NAME/$REPO:latest
